id: IB4426C46
legacy_id: P004510
ocr_import_info:
  bdrc_scan_id: W8LS17296
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T08:52:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:46:56.716518+00:00'
last_modified: 2022-09-04 11:47:01.586276
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17296
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17296
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཙུག་ཏོར་རྣམ་རྒྱལ་མ་ལྷ་དགུའི་སྒྲུབ་ཐབས་སྟོང་མཆོད་ཀྱི་ཆོ་ག
  author: ཐུའུ་བཀྭན ༠༣་བློ་བཟང་ཆོས་ཀྱི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.5053952573322681
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I8LS17306:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17306
      total_pages: 40
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17306.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.5053952573322681
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
